# Generated by Django 5.2.17 on 2026-09-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="allow_station_auto_check_in",
            field=models.BooleanField(default=False),
        ),
    ]
