# Generated by Django 5.2.18 on 2026-10-10 02:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_ticket_allocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="group_label",
            field=models.CharField(default="Group", max_length=80),
        ),
        migrations.AddField(
            model_name="event",
            name="group_mode",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("optional", "Optional"),
                    ("required", "Required"),
                ],
                default="disabled",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_closes_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_deadline_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_opens_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="custom_answers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="EventGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "registration_deadline_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registrations",
                to="events.eventgroup",
            ),
        ),
        migrations.CreateModel(
            name="EventRegistrationQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=80)),
                ("label", models.CharField(max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("short_text", "Short text"),
                            ("long_text", "Long text"),
                            ("single_choice", "Single choice"),
                            ("yes_no", "Yes / no"),
                        ],
                        default="short_text",
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=list)),
                ("is_required", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration_questions",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="eventgroup",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="event_group_unique_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventregistrationquestion",
            constraint=models.UniqueConstraint(
                fields=("event", "key"), name="event_registration_question_unique_key"
            ),
        ),
    ]
