# Generated by Django 5.2.18 on 2026-10-10 12:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_group_label_event_group_mode_and_more"),
        ("participants", "0008_alter_consentdocumentversion_original_pdf"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrailerInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identity", models.CharField(max_length=120, unique=True)),
                ("display_name", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OfflineEventPreparation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prepared", "Prepared"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("blocked", "Blocked"),
                        ],
                        default="prepared",
                        max_length=12,
                    ),
                ),
                ("consent_hash", models.CharField(blank=True, max_length=64)),
                ("sync_identity", models.CharField(blank=True, max_length=120)),
                (
                    "last_readiness_check_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consent_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="participants.consentdocumentversion",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offline_preparations",
                        to="events.event",
                    ),
                ),
                (
                    "trailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_preparations",
                        to="events.trailerinstance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfflineRegistrationEnvelope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("participant_identity", models.UUIDField()),
                ("registration_id", models.UUIDField(blank=True, null=True)),
                ("ticket_number", models.CharField(max_length=10)),
                ("consent_document_version", models.PositiveIntegerField()),
                ("consent_hash", models.CharField(max_length=64)),
                ("group_name", models.CharField(blank=True, max_length=160)),
                ("custom_answers", models.JSONField(blank=True, default=dict)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("synced", "Synced"),
                            ("review", "Needs review"),
                        ],
                        default="local",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "preparation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="events.offlineeventpreparation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfflineTicketRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("primary", "Primary"), ("backup", "Backup")],
                        max_length=8,
                    ),
                ),
                ("start_number", models.BigIntegerField()),
                ("end_number", models.BigIntegerField()),
                ("next_number", models.BigIntegerField()),
                ("is_exhausted", models.BooleanField(default=False)),
                (
                    "preparation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_ranges",
                        to="events.offlineeventpreparation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipantMatchReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("evidence", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.CharField(blank=True, max_length=240)),
                (
                    "candidate_participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="participants.participant",
                    ),
                ),
                (
                    "envelope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_reviews",
                        to="events.offlineregistrationenvelope",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncOutboxItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operation_key", models.CharField(max_length=160, unique=True)),
                ("operation_type", models.CharField(max_length=60)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_flight", "In flight"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_error", models.TextField(blank=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preparation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sync_outbox",
                        to="events.offlineeventpreparation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "Text")], max_length=8
                    ),
                ),
                ("destination_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=160)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="events.eventregistration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BackupRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("storage_path", models.CharField(max_length=500)),
                ("ciphertext_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("succeeded", "Succeeded"), ("failed", "Failed")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "trailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="backups",
                        to="events.trailerinstance",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="offlineregistrationenvelope",
            constraint=models.UniqueConstraint(
                fields=("preparation", "ticket_number"),
                name="offline_ticket_unique_per_prep",
            ),
        ),
        migrations.AddConstraint(
            model_name="offlineticketrange",
            constraint=models.UniqueConstraint(
                fields=("preparation", "kind"), name="offline_range_kind_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="syncoutboxitem",
            index=models.Index(
                fields=["status", "next_attempt_at"], name="sync_outbox_ready_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketdelivery",
            constraint=models.UniqueConstraint(
                fields=("registration", "channel", "destination_hash"),
                name="delivery_destination_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="offlineeventpreparation",
            constraint=models.UniqueConstraint(
                fields=("event", "trailer"), name="offline_prep_event_trailer_unique"
            ),
        ),
    ]
