# Generated by Django 5.2.18 on 2026-10-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_trailerinstance_offlineeventpreparation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CentralSyncReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_key", models.CharField(max_length=200, unique=True)),
                ("trailer_identity", models.CharField(max_length=120)),
                ("event_id", models.UUIDField()),
                ("preparation_id", models.UUIDField(blank=True, null=True)),
                ("participant_identity", models.UUIDField(blank=True, null=True)),
                ("ticket_number", models.CharField(blank=True, max_length=10)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("accepted", "Accepted"), ("review", "Needs review")],
                        default="accepted",
                        max_length=12,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["trailer_identity", "event_id"],
                        name="sync_receipt_scope_idx",
                    )
                ],
            },
        ),
    ]
