# Generated by Django 5.2.17 on 2026-10-07 16:41

import apps.simulators.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_event_allow_station_auto_check_in"),
        ("participants", "0001_initial"),
        ("stations", "0002_alter_experienceactivity_activity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulatorCaptureProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("simulator_type", models.CharField(max_length=120)),
                ("expected_width", models.PositiveIntegerField(blank=True, null=True)),
                ("expected_height", models.PositiveIntegerField(blank=True, null=True)),
                ("identifier_region", models.JSONField(blank=True, default=dict)),
                ("score_region", models.JSONField(blank=True, default=dict)),
                ("state_regions", models.JSONField(blank=True, default=list)),
                (
                    "known_identifier_prefixes",
                    models.JSONField(
                        default=apps.simulators.models.default_identifier_prefixes
                    ),
                ),
                ("profile_version", models.CharField(default="1", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SimulatorCapture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("submission_id", models.UUIDField(unique=True)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("profile_version", models.CharField(max_length=40)),
                ("profile_snapshot", models.JSONField(default=dict)),
                ("raw_identifier", models.CharField(max_length=128)),
                ("normalized_identifier", models.CharField(blank=True, max_length=64)),
                ("raw_total_score", models.CharField(max_length=64)),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("captured_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("matched", "Matched official result"),
                            ("needs_review", "Needs review"),
                            ("resolved", "Resolved official result"),
                            ("test", "Simulator test"),
                        ],
                        default="needs_review",
                        max_length=16,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("staff_test", "Staff test"),
                            ("demo", "Demo"),
                            ("unresolved", "Unresolved"),
                        ],
                        default="unresolved",
                        max_length=16,
                    ),
                ),
                ("is_official", models.BooleanField(default=False)),
                ("review_reason", models.CharField(blank=True, max_length=80)),
                ("diagnostic_metadata", models.JSONField(blank=True, default=dict)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_reason", models.CharField(blank=True, max_length=500)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=500)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simulator_captures",
                        to="events.event",
                    ),
                ),
                (
                    "experience_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simulator_captures",
                        to="stations.experiencesession",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simulator_captures",
                        to="participants.participant",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simulator_captures",
                        to="events.eventregistration",
                    ),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="simulators.simulatorcapture",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_simulator_captures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simulator_captures",
                        to="stations.station",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voided_simulator_captures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="captures",
                        to="simulators.simulatorcaptureprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-received_at",),
                "indexes": [
                    models.Index(
                        fields=["event", "status"], name="simulator_event_status_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_official", True), ("voided_at__isnull", True)
                        ),
                        fields=("experience_session",),
                        name="simulator_one_current_official_result",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventSimulatorConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("simulator_type", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simulator_configurations",
                        to="events.event",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simulator_configurations",
                        to="stations.station",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_configurations",
                        to="simulators.simulatorcaptureprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "station"),
                        name="simulator_event_station_unique",
                    )
                ],
            },
        ),
    ]
