# Generated by Django 5.2.17 on 2026-09-30 20:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_event_allow_station_auto_check_in"),
        ("participants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "station_type",
                    models.CharField(
                        choices=[
                            ("kiosk", "Kiosk"),
                            ("duck", "Duck experience"),
                            ("simulator", "Simulator"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ExperienceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("official", "Official participant"),
                            ("staff_test", "Staff test"),
                            ("demo", "Demo"),
                        ],
                        default="official",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_experience_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="experience_sessions",
                        to="events.event",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="experience_sessions",
                        to="participants.participant",
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="experience_session",
                        to="events.eventregistration",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="ExperienceActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("kiosk", "Kiosk"),
                            ("duck", "Duck experience"),
                            ("simulator", "Simulator"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped by staff"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("skipped_at", models.DateTimeField(blank=True, null=True)),
                ("skip_reason", models.CharField(blank=True, max_length=500)),
                (
                    "skipped_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skipped_experience_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="stations.experiencesession",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="EventStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("is_active_context", models.BooleanField(default=False)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_assignments",
                        to="events.event",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_assignments",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "station__name"),
            },
        ),
        migrations.AddConstraint(
            model_name="experiencesession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("mode", "official"),
                        ("participant__isnull", False),
                        ("registration__isnull", False),
                    ),
                    models.Q(
                        ("mode__in", ("staff_test", "demo")),
                        ("participant__isnull", True),
                        ("registration__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="stations_session_identity_matches_mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="experiencesession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("completed_at__isnull", True),
                    ("completed_at__gte", models.F("started_at")),
                    _connector="OR",
                ),
                name="stations_session_completion_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="experienceactivity",
            constraint=models.UniqueConstraint(
                fields=("session", "activity"), name="stations_unique_session_activity"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventstation",
            constraint=models.UniqueConstraint(
                fields=("event", "station"), name="stations_unique_event_station"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventstation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active_context", True)),
                fields=("station",),
                name="stations_one_active_context_per_station",
            ),
        ),
    ]
