# Generated by Django 5.2.17 on 2026-10-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experienceactivity",
            name="activity",
            field=models.CharField(
                choices=[
                    ("kiosk", "Kiosk"),
                    ("duck", "Legacy Duck experience"),
                    ("game", "Game"),
                    ("simulator", "Simulator"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="station_type",
            field=models.CharField(
                choices=[
                    ("kiosk", "Kiosk"),
                    ("duck", "Legacy Duck experience"),
                    ("game", "Game"),
                    ("simulator", "Simulator"),
                ],
                max_length=20,
            ),
        ),
    ]
