# Generated by Django 5.2.17 on 2026-10-05 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizattempt",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quiz_attempts",
                to="participants.participant",
            ),
        ),
    ]
