# Generated by Django 5.2.17 on 2026-10-08 13:15
from django.db import migrations, models


def classify_legacy_event_pools(apps, schema_editor):
    EventAssessmentCategory = apps.get_model("assessments", "EventAssessmentCategory")
    EventAssessmentCategory.objects.all().update(pool_mode="default")


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0002_alter_quizattempt_participant"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventassessmentcategory",
            name="curated_questions",
            field=models.ManyToManyField(
                blank=True,
                related_name="curated_event_configurations",
                to="assessments.question",
            ),
        ),
        migrations.AddField(
            model_name="eventassessmentcategory",
            name="pool_mode",
            field=models.CharField(
                choices=[
                    ("default", "Default category pool"),
                    ("curated", "Event-specific curated pool"),
                ],
                default="curated",
                max_length=12,
            ),
        ),
        migrations.RunPython(classify_legacy_event_pools, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="eventassessmentcategory",
            name="pool_mode",
            field=models.CharField(
                choices=[
                    ("default", "Default category pool"),
                    ("curated", "Event-specific curated pool"),
                ],
                default="default",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="questionset",
            name="effective_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
