# Generated by Django 5.2.17 on 2026-10-07 23:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_identity_uuids(apps, schema_editor):
    Participant = apps.get_model("participants", "Participant")
    for pk in Participant.objects.using(schema_editor.connection.alias).values_list("pk", flat=True).iterator():
        Participant.objects.using(schema_editor.connection.alias).filter(pk=pk).update(identity_uuid=uuid.uuid4())



class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_allow_station_auto_check_in"),
        ("participants", "0001_initial"),
        ("stations", "0002_alter_experienceactivity_activity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantCareerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employment_status", models.CharField(blank=True, max_length=100)),
                ("career_interests", models.TextField(blank=True)),
                ("work_availability", models.CharField(blank=True, max_length=160)),
                ("willing_to_travel", models.BooleanField(blank=True, null=True)),
                ("education_training", models.TextField(blank=True)),
                ("skills_interests", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestParticipantRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("reset_at", models.DateTimeField(blank=True, null=True)),
                ("reset_reason", models.CharField(blank=True, max_length=240)),
            ],
        ),
        migrations.AddField(
            model_name="participant",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="participant",
            name="identity_uuid",
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(backfill_identity_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="participant",
            name="identity_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="kind",
            field=models.CharField(
                choices=[("person", "Person"), ("system_test", "BTW test identity")],
                default="person",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="postal_code",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="participant",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="participant",
            name="test_qr_token",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "system_test")),
                fields=("kind",),
                name="participants_one_system_test_identity",
            ),
        ),
        migrations.AddField(
            model_name="participantcareerprofile",
            name="participant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="career_profile",
                to="participants.participant",
            ),
        ),
        migrations.AddField(
            model_name="testparticipantrun",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="test_participant_runs",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="testparticipantrun",
            name="experience_session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="test_participant_run",
                to="stations.experiencesession",
            ),
        ),
        migrations.AddField(
            model_name="testparticipantrun",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="test_runs",
                to="participants.participant",
            ),
        ),
        migrations.AddConstraint(
            model_name="testparticipantrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reset_at__isnull", True)),
                fields=("participant", "event"),
                name="participants_one_active_test_run",
            ),
        ),
    ]
