# Generated by Django 5.2.17 on 2026-10-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0003_registrationform_consentdocumentversion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="participant",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="participant",
            name="age_classification",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="participant",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="life_stage",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
