# Generated by Django 5.2.17 on 2026-10-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0004_participant_address_line_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentdocumentversion",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="consentdocumentversion",
            name="original_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="consent_documents/"
            ),
        ),
    ]
