# Generated by Django 5.2.17 on 2026-10-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0006_consentdocumentversion_published_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationsubmission",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
