# Generated by Django 5.2.17 on 2026-10-09 11:25

import apps.participants.consent_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0007_registrationsubmission_idempotency_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consentdocumentversion",
            name="original_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.participants.consent_storage.PrivateConsentStorage(),
                upload_to="consent_documents/",
            ),
        ),
    ]
